edition = "2021"
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
max_width = 100
use_small_heuristics = "Default"
fn_args_layout = "Tall"
newline_style = "Unix"

unstable_features = true

blank_lines_upper_bound = 2
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
match_arm_blocks = false
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
space_after_colon = true
spaces_around_ranges = true
trailing_semicolon = true
where_single_line = true